#!/usr/bin/env python3
"""
build_dossier.py — compiles an ideas/<slug>/ folder into one self-contained dossier.html.

Reads README.md, work/*.md, work/sources.md, work/model_output.json and any
work/model-pivot-*_output.json, renders the markdown, draws the scenario charts as
inline SVG and writes a single HTML file with no external dependencies: it opens
offline, travels by e-mail and prints to PDF.

Usage:
    python3 build_dossier.py ideas/<slug>                     # writes ideas/<slug>/dossier.html
    python3 build_dossier.py ideas/<slug> --out x.html --lang pt --no-research

Only the standard library is used on purpose: the script must run anywhere.
"""

from __future__ import annotations

import argparse
import glob
import html
import json
import math
import os
import re
import sys
from datetime import date

VERDICTS = ("GO", "VALIDATE-FIRST", "PIVOT", "KILL")
VERDICT_STYLE = {
    "GO": ("good", "✓"),
    "VALIDATE-FIRST": ("warning", "?"),
    "PIVOT": ("serious", "↻"),
    "KILL": ("critical", "✕"),
}
SCENARIOS = ("pessimistic", "realistic", "optimistic")
SERIES_SLOT = {"realistic": 1, "pessimistic": 2, "optimistic": 3}
CURRENCY_SYMBOL = {"BRL": "R$", "USD": "US$", "EUR": "€", "GBP": "£", "ARS": "AR$", "MXN": "MX$"}

SECTIONS = [
    ("02-market.md", "market"),
    ("03-competitors.md", "competitors"),
    ("04-customer-and-demand.md", "customer"),
    ("05-financial-model.md", "financials"),
    ("06-go-to-market.md", "gtm"),
    ("07-risks-and-verdict.md", "risks"),
    ("08-validation-plan.md", "validation"),
    ("01-interview.md", "interview"),
    ("00-intake.md", "intake"),
]
COLLAPSED_SECTIONS = {"interview", "intake"}

LABELS = {
    "en": {
        "summary": "Summary",
        "numbers": "The numbers",
        "market": "Market",
        "competitors": "Competitors",
        "customer": "Customer & demand",
        "financials": "Financial model",
        "gtm": "Go-to-market",
        "risks": "Risks & verdict",
        "validation": "Validation plan",
        "interview": "Interview",
        "intake": "Intake",
        "sources": "Sources",
        "research": "Research notes",
        "pessimistic": "Pessimistic",
        "realistic": "Realistic",
        "optimistic": "Optimistic",
        "founder_goal": "Each founder earns {target}/month",
        "be_users": "Customers to break even (sustainable)",
        "first_profit": "First profitable month",
        "cash_positive": "Cash-positive month",
        "peak_cash": "Cash needed (peak)",
        "users_at": "Customers at month {m}",
        "mrr_at": "MRR at month {m}",
        "arr_end": "ARR at month {m}",
        "ltv_cac": "LTV / CAC",
        "payback": "CAC payback",
        "gross_margin": "Gross margin",
        "chart_users": "Active customers by month",
        "chart_cash": "Cumulative cash by month",
        "chart_sens": "Sensitivity of sustainable break-even (realistic, ±20 % per lever)",
        "sens_better": "fewer customers needed",
        "sens_worse": "more customers needed",
        "break_even_ref": "break-even (realistic)",
        "market_title": "Market sizing from the model inputs",
        "tam": "TAM",
        "sam": "SAM",
        "som": "SOM (year 3)",
        "customers": "customers",
        "annual_revenue": "annual revenue",
        "warnings": "Model warnings",
        "pivots": "Escape routes, re-costed",
        "pivot": "Pivot",
        "never": "never",
        "month": "month {m}",
        "months": "{m} months",
        "table": "Table view",
        "verdict": "Verdict",
        "verdict_meta": "Built {date} from the dossier files · every number carries a tag and a source in the sections below",
        "footer": "Generated by grill-my-idea · build_dossier.py · the markdown sources live in work/",
        "menu": "Contents",
        "no_model": "No model output found (work/model_output.json). Run financial_model.py first.",
        "missing": "Missing: {name}",
        "print": "Print / PDF",
        "of_sam": "of SAM",
    },
    "pt": {
        "summary": "Resumo",
        "numbers": "Os números",
        "market": "Mercado",
        "competitors": "Concorrentes",
        "customer": "Cliente e demanda",
        "financials": "Modelo financeiro",
        "gtm": "Go-to-market",
        "risks": "Riscos e veredito",
        "validation": "Plano de validação",
        "interview": "Entrevista",
        "intake": "Intake",
        "sources": "Fontes",
        "research": "Notas de pesquisa",
        "pessimistic": "Pessimista",
        "realistic": "Realista",
        "optimistic": "Otimista",
        "founder_goal": "Cada fundador ganha {target}/mês",
        "be_users": "Clientes para o break-even (sustentável)",
        "first_profit": "Primeiro mês lucrativo",
        "cash_positive": "Mês de caixa positivo",
        "peak_cash": "Caixa necessário (pico)",
        "users_at": "Clientes no mês {m}",
        "mrr_at": "MRR no mês {m}",
        "arr_end": "ARR no mês {m}",
        "ltv_cac": "LTV / CAC",
        "payback": "Payback do CAC",
        "gross_margin": "Margem bruta",
        "chart_users": "Clientes ativos por mês",
        "chart_cash": "Caixa acumulado por mês",
        "chart_sens": "Sensibilidade do break-even sustentável (realista, ±20 % por alavanca)",
        "sens_better": "menos clientes necessários",
        "sens_worse": "mais clientes necessários",
        "break_even_ref": "break-even (realista)",
        "market_title": "Tamanho de mercado a partir dos inputs do modelo",
        "tam": "TAM",
        "sam": "SAM",
        "som": "SOM (ano 3)",
        "customers": "clientes",
        "annual_revenue": "receita anual",
        "warnings": "Alertas do modelo",
        "pivots": "Rotas de fuga, recalculadas",
        "pivot": "Pivô",
        "never": "nunca",
        "month": "mês {m}",
        "months": "{m} meses",
        "table": "Ver tabela",
        "verdict": "Veredito",
        "verdict_meta": "Gerado em {date} a partir dos arquivos do dossiê · cada número carrega tag e fonte nas seções abaixo",
        "footer": "Gerado por grill-my-idea · build_dossier.py · as fontes em markdown ficam em work/",
        "menu": "Conteúdo",
        "no_model": "Saída do modelo não encontrada (work/model_output.json). Rode financial_model.py primeiro.",
        "missing": "Faltando: {name}",
        "print": "Imprimir / PDF",
        "of_sam": "do SAM",
    },
}

LEVER_NAMES = {
    "arpu_monthly": "ARPU",
    "monthly_churn": "Churn",
    "cac": "CAC",
    "fixed_costs_monthly": "Fixed costs",
    "cogs_per_user_monthly": "COGS / customer",
    "organic_new_users_monthly": "Organic new customers",
    "marketing_budget_monthly": "Marketing budget",
    "take_rate": "Take rate",
    "gmv_per_user_monthly": "GMV / customer",
    "tax_rate_on_revenue": "Tax rate",
    "payment_fee_pct_of_gmv": "Payment fee",
}


def fail(msg: str) -> None:
    print(f"error: {msg}", file=sys.stderr)
    sys.exit(1)


# ---------------------------------------------------------------- formatting

def fmt_num(x, lang: str, digits: int = 0) -> str:
    if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))):
        return "—"
    s = f"{x:,.{digits}f}"
    if lang == "pt":
        s = s.translate(str.maketrans(",.", ".,"))
    return s


def fmt_money(x, cur: str, lang: str) -> str:
    if x is None or (isinstance(x, float) and (math.isnan(x) or math.isinf(x))):
        return "—"
    sym = CURRENCY_SYMBOL.get(cur, cur + " ")
    return f"{sym} {fmt_num(round(x), lang)}"


def fmt_compact(x: float, cur: str | None = None) -> str:
    sign = "-" if x < 0 else ""
    a = abs(x)
    if a >= 1e9:
        s = f"{a / 1e9:.1f}B"
    elif a >= 1e6:
        s = f"{a / 1e6:.1f}M"
    elif a >= 1e3:
        s = f"{a / 1e3:.0f}k" if a >= 1e4 else f"{a / 1e3:.1f}k"
    else:
        s = f"{a:.0f}"
    s = s.replace(".0k", "k").replace(".0M", "M").replace(".0B", "B")
    sym = (CURRENCY_SYMBOL.get(cur, cur) + " ") if cur else ""
    return f"{sign}{sym}{s}"


def fmt_month(m, L: dict) -> str:
    if m is None:
        return L["never"]
    return L["month"].format(m=int(m))


def fmt_pct(x, lang: str, digits: int = 0) -> str:
    if x is None:
        return "—"
    return fmt_num(x * 100, lang, digits) + " %"


def nice_ticks(lo: float, hi: float, n: int = 5) -> list[float]:
    if hi <= lo:
        hi = lo + 1
    raw = (hi - lo) / n
    mag = 10 ** math.floor(math.log10(raw))
    for mult in (1, 2, 2.5, 5, 10):
        step = mult * mag
        if raw <= step:
            break
    start = math.floor(lo / step) * step
    ticks = []
    v = start
    while v < hi + step * 0.999:
        ticks.append(round(v, 10))
        v += step
    return ticks


# ---------------------------------------------------------------- markdown → html

def esc(s: str) -> str:
    return html.escape(s, quote=False)


def slugify(s: str) -> str:
    s = re.sub(r"[^\w\s-]", "", s.lower(), flags=re.UNICODE)
    return re.sub(r"[\s_-]+", "-", s).strip("-") or "s"


TAG_RE = re.compile(
    r"\[(data|benchmark|estimate|guess|fact|belief|assumption|unknown|blocker|major|minor)"
    r"(?::\s*([^\]]*))?\]",
    re.IGNORECASE,
)
SRC_RE = re.compile(r"\[S(\d+)\]")
SRC_INLINE_RE = re.compile(r"(?<![\w#])S(\d{1,3})(?![\w])")


def render_tags(s: str) -> str:
    def tag(m: re.Match) -> str:
        kind = m.group(1).lower()
        detail = m.group(2)
        body = kind.upper() if kind in ("blocker", "major", "minor") else kind
        if detail:
            detail = SRC_INLINE_RE.sub(r'<a class="src" href="#S\1">S\1</a>', esc(detail))
            return f'<span class="tag tag-{kind}">{body}<span class="tag-detail">{detail}</span></span>'
        return f'<span class="tag tag-{kind}">{body}</span>'

    s = TAG_RE.sub(tag, s)
    s = SRC_RE.sub(r'<a class="src" href="#S\1">[S\1]</a>', s)
    return s


def inline(text: str) -> str:
    codes: list[str] = []

    def stash(m: re.Match) -> str:
        codes.append(f"<code>{esc(m.group(1))}</code>")
        return f"\x01{len(codes) - 1}\x02"

    text = re.sub(r"`([^`\n]+)`", stash, text)
    text = esc(text)
    text = re.sub(r"!\[([^\]]*)\]\(([^)\s]+)\)", r'<img alt="\1" src="\2">', text)
    text = re.sub(r"\[([^\]]+)\]\(([^)\s]+)\)", r'<a href="\2">\1</a>', text)
    text = re.sub(r"&lt;(https?://[^&\s]+)&gt;", r'<a href="\1">\1</a>', text)
    text = re.sub(r"(?<![\"'>=])(https?://[^\s<)\]]+)", r'<a href="\1">\1</a>', text)
    text = re.sub(r"\*\*(.+?)\*\*", r"<strong>\1</strong>", text)
    text = re.sub(r"__(.+?)__", r"<strong>\1</strong>", text)
    text = re.sub(r"(?<![\w*])\*(?!\s)(.+?)(?<!\s)\*(?![\w*])", r"<em>\1</em>", text)
    text = re.sub(r"(?<![\w])_(?!\s)([^_]+?)(?<!\s)_(?![\w])", r"<em>\1</em>", text)
    text = re.sub(r"~~(.+?)~~", r"<del>\1</del>", text)
    text = render_tags(text)
    text = text.replace("  \n", "<br>\n")
    return re.sub(r"\x01(\d+)\x02", lambda m: codes[int(m.group(1))], text)


HEADING_RE = re.compile(r"^(#{1,6})\s+(.*?)\s*#*\s*$")
FENCE_RE = re.compile(r"^(```|~~~)\s*(\w+)?\s*$")
HR_RE = re.compile(r"^\s*([-*_])(\s*\1){2,}\s*$")
LIST_RE = re.compile(r"^(\s*)([-*+]|\d+[.)])\s+(.*)$")
TABLE_SEP_RE = re.compile(r"^\s*\|?\s*:?-{2,}:?\s*(\|\s*:?-{2,}:?\s*)*\|?\s*$")
QUOTE_RE = re.compile(r"^\s{0,3}>\s?(.*)$")


def split_row(line: str) -> list[str]:
    line = line.strip()
    if line.startswith("|"):
        line = line[1:]
    if line.endswith("|") and not line.endswith("\\|"):
        line = line[:-1]
    cells = re.split(r"(?<!\\)\|", line)
    return [c.strip().replace("\\|", "|") for c in cells]


def render_table(rows: list[str]) -> str:
    header = split_row(rows[0])
    aligns = []
    for c in split_row(rows[1]):
        left, right = c.startswith(":"), c.endswith(":")
        aligns.append("center" if left and right else "right" if right else "left")
    out = ['<div class="table-wrap"><table>', "<thead><tr>"]
    for i, c in enumerate(header):
        a = aligns[i] if i < len(aligns) else "left"
        out.append(f'<th class="al-{a}">{inline(c)}</th>')
    out.append("</tr></thead><tbody>")
    for r in rows[2:]:
        cells = split_row(r)
        out.append("<tr>")
        for i in range(len(header)):
            c = cells[i] if i < len(cells) else ""
            a = aligns[i] if i < len(aligns) else "left"
            out.append(f'<td class="al-{a}">{inline(c)}</td>')
        out.append("</tr>")
    out.append("</tbody></table></div>")
    return "".join(out)


def render_list(block: list[str], shift: int, prefix: str) -> str:
    first = LIST_RE.match(block[0])
    base_indent = len(first.group(1))
    ordered = first.group(2)[0].isdigit()
    items: list[list[str]] = []
    for line in block:
        m = LIST_RE.match(line)
        if m and len(m.group(1)) <= base_indent:
            items.append([m.group(3)])
        elif items:
            items[-1].append(line)
    out = ["<ol>" if ordered else "<ul>"]
    for it in items:
        head, rest = it[0], it[1:]
        while rest and not rest[-1].strip():
            rest.pop()
        if rest:
            strip = min(len(l) - len(l.lstrip()) for l in rest if l.strip())
            body = [l[strip:] if l.strip() else "" for l in rest]
            if any(LIST_RE.match(l) or not l.strip() for l in body):
                out.append(f"<li>{inline(head)}{md_to_html(chr(10).join(body), shift, prefix)}</li>")
            else:
                out.append(f"<li>{inline(head + ' ' + ' '.join(l.strip() for l in body))}</li>")
        else:
            out.append(f"<li>{inline(head)}</li>")
    out.append("</ol>" if ordered else "</ul>")
    return "".join(out)


def md_to_html(text: str, shift: int = 0, prefix: str = "") -> str:
    lines = text.replace("\r\n", "\n").split("\n")
    out: list[str] = []
    i, n = 0, len(lines)
    while i < n:
        line = lines[i]
        if not line.strip():
            i += 1
            continue
        fence = FENCE_RE.match(line)
        if fence:
            marker, lang = fence.group(1), fence.group(2)
            j = i + 1
            code = []
            while j < n and not lines[j].startswith(marker):
                code.append(lines[j])
                j += 1
            cls = f' class="lang-{lang}"' if lang else ""
            out.append(f"<pre><code{cls}>{esc(chr(10).join(code))}</code></pre>")
            i = j + 1
            continue
        h = HEADING_RE.match(line)
        if h:
            level = min(6, len(h.group(1)) + shift)
            title = h.group(2)
            hid = f"{prefix}-{slugify(title)}" if prefix else slugify(title)
            out.append(f'<h{level} id="{hid}">{inline(title)}</h{level}>')
            i += 1
            continue
        if HR_RE.match(line):
            out.append("<hr>")
            i += 1
            continue
        if "|" in line and i + 1 < n and TABLE_SEP_RE.match(lines[i + 1]) and "|" in lines[i + 1]:
            j = i
            rows = []
            while j < n and lines[j].strip() and "|" in lines[j]:
                rows.append(lines[j])
                j += 1
            out.append(render_table(rows))
            i = j
            continue
        if QUOTE_RE.match(line):
            j = i
            quote = []
            while j < n and lines[j].strip() and (QUOTE_RE.match(lines[j]) or quote):
                q = QUOTE_RE.match(lines[j])
                quote.append(q.group(1) if q else lines[j])
                j += 1
                if j < n and not lines[j].strip():
                    break
            out.append(f"<blockquote>{md_to_html(chr(10).join(quote), shift, prefix)}</blockquote>")
            i = j
            continue
        if LIST_RE.match(line):
            j = i
            block = []
            while j < n:
                cur = lines[j]
                if not cur.strip():
                    nxt = lines[j + 1] if j + 1 < n else ""
                    if nxt.strip() and (LIST_RE.match(nxt) or nxt.startswith("  ")):
                        block.append(cur)
                        j += 1
                        continue
                    break
                if LIST_RE.match(cur) or cur.startswith("  ") or cur.startswith("\t") or (block and not LIST_RE.match(cur) and not HEADING_RE.match(cur) and not block[-1].strip() == ""):
                    block.append(cur)
                    j += 1
                    continue
                break
            out.append(render_list(block, shift, prefix))
            i = j
            continue
        j = i
        para = []
        while j < n and lines[j].strip() and not (
            HEADING_RE.match(lines[j]) or FENCE_RE.match(lines[j]) or HR_RE.match(lines[j])
            or QUOTE_RE.match(lines[j]) or LIST_RE.match(lines[j])
            or ("|" in lines[j] and j + 1 < n and TABLE_SEP_RE.match(lines[j + 1]))
        ):
            para.append(lines[j])
            j += 1
        if not para:
            para.append(line)
            j = i + 1
        out.append(f"<p>{inline(chr(10).join(para))}</p>")
        i = j
    return "\n".join(out)


# ---------------------------------------------------------------- dossier files

def read_text(dossier: str, name: str) -> str | None:
    for candidate in (os.path.join(dossier, "work", name), os.path.join(dossier, name)):
        if os.path.isfile(candidate):
            with open(candidate, encoding="utf-8") as f:
                return f.read()
    return None


def read_json(path: str) -> dict | None:
    if not os.path.isfile(path):
        return None
    with open(path, encoding="utf-8") as f:
        return json.load(f)


def split_title(md: str) -> tuple[str | None, str]:
    lines = md.replace("\r\n", "\n").split("\n")
    for idx, line in enumerate(lines):
        if not line.strip():
            continue
        h = HEADING_RE.match(line)
        if h and len(h.group(1)) == 1:
            return h.group(2), "\n".join(lines[idx + 1:])
        break
    return None, md


def parse_readme(md: str) -> dict:
    title, body = split_title(md)
    verdict = None
    name = title or ""
    if title:
        m = re.search(r"(GO|VALIDATE-FIRST|PIVOT|KILL)\b", title)
        if m:
            verdict = m.group(1)
        name = re.split(r"\s+[—–-]+\s+Verdict", title)[0].strip()
        name = re.sub(r"\s*[—–-]?\s*Verdict:.*$", "", name).strip() or title
    lines = body.split("\n")
    meta: list[str] = []
    quote: list[str] = []
    rest_start = 0
    idx = 0
    while idx < len(lines) and not lines[idx].strip():
        idx += 1
    if idx < len(lines) and "·" in lines[idx] and not HEADING_RE.match(lines[idx]) and not QUOTE_RE.match(lines[idx]):
        meta = [m.strip() for m in lines[idx].split("·") if m.strip()]
        idx += 1
    while idx < len(lines) and not lines[idx].strip():
        idx += 1
    while idx < len(lines) and QUOTE_RE.match(lines[idx]):
        quote.append(QUOTE_RE.match(lines[idx]).group(1))
        idx += 1
    rest_start = idx
    return {
        "name": name,
        "verdict": verdict,
        "meta": meta,
        "quote": "\n".join(quote).strip(),
        "body": "\n".join(lines[rest_start:]),
    }


def scenario_summary(sc: dict) -> dict:
    sim, ue = sc.get("sim", {}), sc.get("ue", {})
    return {
        "goal": sim.get("founder_income_month"),
        "goal_target": sim.get("founder_income_target_monthly"),
        "founders": sim.get("founders", 1),
        "be_users": ue.get("breakeven_users_sustainable"),
        "first_profit": sim.get("first_profitable_month"),
        "cash_positive": sim.get("cash_positive_month"),
        "peak_cash": sim.get("peak_cash_need"),
        "users_m12": sim.get("users_m12"),
        "users_end": sim.get("users_end"),
        "mrr_end": (sim.get("rows") or [{}])[-1].get("revenue"),
        "arr_end": sim.get("arr_end"),
        "ltv_cac": ue.get("ltv_cac"),
        "payback": ue.get("cac_payback_months"),
        "gross_margin": ue.get("gross_margin"),
        "rows": sim.get("rows") or [],
    }


# ---------------------------------------------------------------- svg charts

def svg_text(x: float, y: float, s: str, cls: str, anchor: str = "start") -> str:
    return f'<text x="{x:.1f}" y="{y:.1f}" class="{cls}" text-anchor="{anchor}">{esc(s)}</text>'


def line_chart(cid: str, series: list[dict], horizon: int, cur: str | None, L: dict, lang: str,
               ref: tuple[float, str] | None = None) -> str:
    W, H = 640, 300
    PL, PR, PT, PB = 60, 92, 14, 34
    all_vals = [v for s in series for v in s["values"] if v is not None]
    lo, hi = min(0.0, min(all_vals)), max(all_vals)
    if ref and ref[0] is not None and ref[0] < hi * 3:
        hi = max(hi, ref[0])
    ticks = nice_ticks(lo, hi)
    lo, hi = ticks[0], ticks[-1]

    def x(m: float) -> float:
        return PL + (m - 1) / max(1, horizon - 1) * (W - PL - PR)

    def y(v: float) -> float:
        return PT + (hi - v) / (hi - lo) * (H - PT - PB)

    parts = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-labelledby="{cid}-t">']
    parts.append(f'<title id="{cid}-t">{esc(L["chart_users"] if "users" in cid else L["chart_cash"])}</title>')
    for t in ticks:
        parts.append(f'<line x1="{PL}" x2="{W - PR}" y1="{y(t):.1f}" y2="{y(t):.1f}" class="grid"/>')
        parts.append(svg_text(PL - 8, y(t) + 4, fmt_compact(t, cur), "axis", "end"))
    step = 6 if horizon > 24 else 3
    for m in range(1, horizon + 1):
        if m == 1 or m % step == 0:
            parts.append(svg_text(x(m), H - PB + 18, f"m{m}", "axis", "middle"))
    if lo < 0 < hi:
        parts.append(f'<line x1="{PL}" x2="{W - PR}" y1="{y(0):.1f}" y2="{y(0):.1f}" class="zero"/>')
    else:
        parts.append(f'<line x1="{PL}" x2="{W - PR}" y1="{y(lo):.1f}" y2="{y(lo):.1f}" class="baseline"/>')
    if ref and ref[0] is not None and lo <= ref[0] <= hi:
        parts.append(f'<line x1="{PL}" x2="{W - PR}" y1="{y(ref[0]):.1f}" y2="{y(ref[0]):.1f}" class="ref"/>')
        parts.append(svg_text(PL + 6, y(ref[0]) - 6, f"{ref[1]} · {fmt_num(round(ref[0]), lang)}", "ref-label"))
    labels = []
    for s in series:
        pts = " ".join(f"{x(i + 1):.1f},{y(v):.1f}" for i, v in enumerate(s["values"]) if v is not None)
        parts.append(f'<polyline points="{pts}" class="series s{s["slot"]}"/>')
        last = next((v for v in reversed(s["values"]) if v is not None), None)
        if last is not None:
            labels.append([y(last), s["label"], s["slot"]])
    labels.sort(key=lambda r: r[0])
    for k in range(1, len(labels)):
        if labels[k][0] - labels[k - 1][0] < 13:
            labels[k][0] = labels[k - 1][0] + 13
    for ly, label, slot in labels:
        parts.append(f'<circle cx="{W - PR:.1f}" cy="{ly:.1f}" r="3" class="dot s{slot}"/>')
        parts.append(svg_text(W - PR + 8, ly + 4, label, "end-label"))
    parts.append(f'<line class="xhair" x1="0" x2="0" y1="{PT}" y2="{H - PB}" hidden/>')
    parts.append(f'<rect class="hit" x="{PL}" y="{PT}" width="{W - PL - PR}" height="{H - PT - PB}"/>')
    parts.append("</svg>")
    data = {
        "x0": PL, "x1": W - PR, "w": W, "horizon": horizon, "cur": cur or "",
        "lang": lang,
        "series": [{"label": s["label"], "slot": s["slot"], "values": [None if v is None else round(v, 2) for v in s["values"]]} for s in series],
    }
    legend = "".join(f'<span class="lg"><i class="sw s{s["slot"]}"></i>{esc(s["label"])}</span>' for s in series)
    return (
        f'<figure class="chart line" id="{cid}" data-kind="line" data-chart=\'{esc(json.dumps(data)).replace(chr(39), "&#39;")}\'>'
        f'<div class="legend">{legend}</div>{"".join(parts)}<div class="tip" hidden></div></figure>'
    )


def checkpoint_table(series: list[dict], horizon: int, cur: str | None, lang: str, L: dict) -> str:
    months = [m for m in (3, 6, 12, 18, 24, 30, 36, 48, 60) if m <= horizon]
    if horizon not in months:
        months.append(horizon)
    out = ['<details class="table-view"><summary>', esc(L["table"]), "</summary>",
           '<div class="table-wrap"><table><thead><tr><th></th>']
    out += [f'<th class="al-right">m{m}</th>' for m in months]
    out.append("</tr></thead><tbody>")
    for s in series:
        out.append(f"<tr><td>{esc(s['label'])}</td>")
        for m in months:
            v = s["values"][m - 1] if m - 1 < len(s["values"]) else None
            out.append(f'<td class="al-right">{fmt_money(v, cur, lang) if cur else fmt_num(v, lang)}</td>')
        out.append("</tr>")
    out.append("</tbody></table></div></details>")
    return "".join(out)


def tornado(sens: list[dict], lang: str, L: dict) -> str:
    rows = []
    for r in sens:
        ref = (r.get("reference") or {}).get("breakeven_users_sustainable")
        lo = (r.get("minus20") or {}).get("breakeven_users_sustainable")
        hi = (r.get("plus20") or {}).get("breakeven_users_sustainable")
        if ref is None:
            continue
        rows.append((LEVER_NAMES.get(r["lever"], r["lever"].replace("_", " ").capitalize()), ref, lo, hi))
    if not rows:
        return ""
    rows.sort(key=lambda t: max(abs((t[2] or t[1]) - t[1]), abs((t[3] or t[1]) - t[1])), reverse=True)
    maxd = max(max(abs((r[2] or r[1]) - r[1]), abs((r[3] or r[1]) - r[1])) for r in rows) or 1
    W, LBL, PADR = 720, 170, 70
    row_h, bar_h = 34, 11
    H = 20 + row_h * len(rows) + 10
    cx = LBL + (W - LBL - PADR) / 2
    scale = (W - LBL - PADR) / 2 / maxd
    parts = [f'<svg viewBox="0 0 {W} {H}" role="img" aria-label="{esc(L["chart_sens"])}">']
    parts.append(f'<line x1="{cx:.1f}" x2="{cx:.1f}" y1="12" y2="{H - 8}" class="zero"/>')
    ref0 = rows[0][1]
    parts.append(svg_text(cx, 10, fmt_num(round(ref0), lang), "axis", "middle"))
    for k, (name, ref, lo, hi) in enumerate(rows):
        top = 20 + k * row_h
        parts.append(svg_text(LBL - 10, top + row_h / 2 + 4, name, "row-label", "end"))
        for j, (val, sign_label) in enumerate(((lo, "−20 %"), (hi, "+20 %"))):
            by = top + 4 + j * (bar_h + 3)
            parts.append(svg_text(LBL - 10, by + bar_h - 2, "", "axis", "end"))
            if val is None:
                parts.append(svg_text(cx + 6, by + bar_h - 2, f"{sign_label}: ∞", "axis"))
                continue
            d = val - ref
            w = abs(d) * scale
            cls = "better" if d < 0 else "worse"
            x0 = cx - w if d < 0 else cx
            parts.append(f'<rect x="{x0:.1f}" y="{by}" width="{max(w, 1):.1f}" height="{bar_h}" rx="2" class="bar {cls}"><title>{esc(name)} {sign_label}: {fmt_num(round(val), lang)}</title></rect>')
            tx = (cx + 6, "start") if w < 4 else (x0 - 5, "end") if d < 0 else (cx + w + 5, "start")
            parts.append(svg_text(tx[0], by + bar_h - 2, f"{sign_label}: {fmt_num(round(val), lang)}", "axis", tx[1]))
    parts.append("</svg>")
    legend = (f'<span class="lg"><i class="sw better"></i>{esc(L["sens_better"])}</span>'
              f'<span class="lg"><i class="sw worse"></i>{esc(L["sens_worse"])}</span>')
    return f'<figure class="chart tornado" data-kind="bar"><div class="legend">{legend}</div>{"".join(parts)}</figure>'


# ---------------------------------------------------------------- page blocks

def numbers_section(model: dict | None, pivots: list[tuple[str, dict]], L: dict, lang: str) -> str:
    if not model:
        return f'<section id="numbers"><h2>{esc(L["numbers"])}</h2><p class="callout warn">{esc(L["no_model"])}</p></section>'
    cur = model.get("currency", "BRL")
    horizon = int(model.get("horizon_months", 36))
    scs = {k: scenario_summary(model["scenarios"][k]) for k in SCENARIOS if k in model.get("scenarios", {})}
    out = [f'<section id="numbers"><h2>{esc(L["numbers"])}</h2>']

    out.append('<div class="cards">')
    for name in SCENARIOS:
        if name not in scs:
            continue
        s = scs[name]
        rows = []
        if s["goal_target"]:
            rows.append((L["founder_goal"].format(target=fmt_money(s["goal_target"], cur, lang)), fmt_month(s["goal"], L), True))
        rows.append((L["be_users"], fmt_num(None if s["be_users"] is None else math.ceil(s["be_users"]), lang), True))
        rows.append((L["first_profit"], fmt_month(s["first_profit"], L), False))
        rows.append((L["peak_cash"], fmt_money(s["peak_cash"], cur, lang), False))
        rows.append((L["users_at"].format(m=12), fmt_num(None if s["users_m12"] is None else round(s["users_m12"]), lang), False))
        rows.append((L["users_at"].format(m=horizon), fmt_num(None if s["users_end"] is None else round(s["users_end"]), lang), False))
        rows.append((L["mrr_at"].format(m=horizon), fmt_money(s["mrr_end"], cur, lang), False))
        rows.append((L["ltv_cac"], fmt_num(s["ltv_cac"], lang, 1) + "×" if s["ltv_cac"] is not None else "∞", False))
        rows.append((L["payback"], L["months"].format(m=fmt_num(s["payback"], lang, 1)) if s["payback"] is not None else "∞", False))
        cls = "card realistic" if name == "realistic" else "card"
        out.append(f'<article class="{cls}"><h3><i class="sw s{SERIES_SLOT[name]}"></i>{esc(L[name])}</h3><dl>')
        for label, value, big in rows:
            out.append(f'<div class="{"kv big" if big else "kv"}"><dt>{esc(label)}</dt><dd>{esc(value)}</dd></div>')
        out.append("</dl></article>")
    out.append("</div>")

    series_users, series_cash = [], []
    for name in SCENARIOS:
        if name not in scs:
            continue
        rows = scs[name]["rows"]
        series_users.append({"label": L[name], "slot": SERIES_SLOT[name], "values": [r.get("users") for r in rows]})
        series_cash.append({"label": L[name], "slot": SERIES_SLOT[name], "values": [r.get("cumulative_cash") for r in rows]})
    be_ref = scs.get("realistic", {}).get("be_users")
    out.append('<div class="charts">')
    out.append(f'<div class="chart-block"><h3>{esc(L["chart_users"])}</h3>')
    out.append(line_chart("chart-users", series_users, horizon, None, L, lang, (be_ref, L["break_even_ref"]) if be_ref else None))
    out.append(checkpoint_table(series_users, horizon, None, lang, L))
    out.append("</div>")
    out.append(f'<div class="chart-block"><h3>{esc(L["chart_cash"])}</h3>')
    out.append(line_chart("chart-cash", series_cash, horizon, cur, L, lang))
    out.append(checkpoint_table(series_cash, horizon, cur, lang, L))
    out.append("</div></div>")

    mk = model.get("market")
    if mk and (mk.get("tam_users") or mk.get("sam_users")):
        out.append(f'<h3>{esc(L["market_title"])}</h3><div class="market">')
        be = scs.get("realistic", {}).get("be_users")
        for key, label in (("tam", L["tam"]), ("sam", L["sam"]), ("som", L["som"])):
            users = mk.get("som_users_year3") if key == "som" else mk.get(f"{key}_users")
            rev = mk.get(f"{key}_annual_revenue")
            if not users:
                continue
            extra = ""
            if key == "sam" and be and users:
                extra = f'<small>break-even = {fmt_pct(be / users, lang, 1)} {esc(L["of_sam"])}</small>'
            if key == "som" and mk.get("som_share_year3"):
                extra = f'<small>{fmt_pct(mk["som_share_year3"], lang, 1)} {esc(L["of_sam"])}</small>'
            out.append(f'<div class="tile {key}"><span class="tile-label">{esc(label)}</span>'
                       f'<span class="tile-value">{fmt_num(round(users), lang)}</span><span class="tile-sub">{esc(L["customers"])}</span>'
                       f'<span class="tile-value2">{fmt_money(rev, cur, lang)}</span><span class="tile-sub">{esc(L["annual_revenue"])}</span>{extra}</div>')
        out.append("</div>")

    sens = model.get("sensitivity") or []
    t = tornado(sens, lang, L)
    if t:
        out.append(f'<div class="chart-block"><h3>{esc(L["chart_sens"])}</h3>{t}</div>')

    if pivots:
        out.append(f'<h3>{esc(L["pivots"])}</h3><div class="table-wrap"><table><thead><tr>'
                   f'<th>{esc(L["pivot"])}</th><th class="al-right">{esc(L["be_users"])}</th>'
                   f'<th class="al-right">{esc(L["first_profit"])}</th><th class="al-right">{esc(L["peak_cash"])}</th>'
                   f'<th class="al-right">{esc(L["users_at"].format(m=horizon))}</th></tr></thead><tbody>')
        base = scs.get("realistic")
        if base:
            out.append(f'<tr><td><em>{esc(L["realistic"])}</em></td><td class="al-right">{fmt_num(None if base["be_users"] is None else math.ceil(base["be_users"]), lang)}</td>'
                       f'<td class="al-right">{fmt_month(base["first_profit"], L)}</td><td class="al-right">{fmt_money(base["peak_cash"], cur, lang)}</td>'
                       f'<td class="al-right">{fmt_num(None if base["users_end"] is None else round(base["users_end"]), lang)}</td></tr>')
        for pname, pm in pivots:
            ps = scenario_summary(pm["scenarios"]["realistic"])
            pcur = pm.get("currency", cur)
            out.append(f'<tr><td>{esc(pname)}</td><td class="al-right">{fmt_num(None if ps["be_users"] is None else math.ceil(ps["be_users"]), lang)}</td>'
                       f'<td class="al-right">{fmt_month(ps["first_profit"], L)}</td><td class="al-right">{fmt_money(ps["peak_cash"], pcur, lang)}</td>'
                       f'<td class="al-right">{fmt_num(None if ps["users_end"] is None else round(ps["users_end"]), lang)}</td></tr>')
        out.append("</tbody></table></div>")

    if model.get("warnings"):
        out.append(f'<div class="callout warn"><strong>{esc(L["warnings"])}</strong><ul>')
        out += [f"<li>{inline(w)}</li>" for w in model["warnings"]]
        out.append("</ul></div>")
    out.append("</section>")
    return "".join(out)


def sources_section(md: str | None, L: dict) -> str:
    if not md:
        return ""
    _, body = split_title(md)
    out = md_to_html(body, 1, "sources")
    ref = r'(?:<a class="src" href="#S\d+">)?\[?S(\d+)\]?(?:</a>)?'
    out = re.sub(rf'<td class="al-(\w+)">{ref}</td>', r'<td class="al-\1" id="S\2">S\2</td>', out)
    out = re.sub(rf'<li>{ref}(\s*[:—–-]?\s*)', r'<li id="S\1">S\1\2', out)
    return f'<section id="sources"><h2>{esc(L["sources"])}</h2>{out}</section>'


def research_section(dossier: str, L: dict) -> str:
    files = sorted(glob.glob(os.path.join(dossier, "work", "research", "*.md")) or glob.glob(os.path.join(dossier, "research", "*.md")))
    if not files:
        return ""
    files.sort(key=lambda p: (0 if os.path.basename(p) == "summary.md" else 1, p))
    out = [f'<section id="research"><h2>{esc(L["research"])}</h2>']
    for p in files:
        with open(p, encoding="utf-8") as f:
            md = f.read()
        title, body = split_title(md)
        base = os.path.splitext(os.path.basename(p))[0]
        out.append(f'<details class="research"><summary>{esc(title or base)}</summary>{md_to_html(body, 2, "research-" + base)}</details>')
    out.append("</section>")
    return "".join(out)


CSS = r"""
:root{color-scheme:light;
--page:#f9f9f7;--surface:#fcfcfb;--surface-2:#f1f0ec;--ink:#0b0b0b;--ink-2:#52514e;--muted:#898781;
--grid:#e1e0d9;--baseline:#c3c2b7;--border:rgba(11,11,11,.10);--accent:#2a78d6;
--s1:#2a78d6;--s2:#eb6834;--s3:#1baf7a;--better:#2a78d6;--worse:#e34948;
--good:#0ca30c;--warning:#fab219;--serious:#ec835a;--critical:#d03b3b;
--tag-data:#0d366b;--tag-data-bg:#cde2fb;--tag-bench:#104281;--tag-bench-bg:#e1ecfa;
--tag-est:#7a4d00;--tag-est-bg:#fdecc8;--tag-guess:#7a1d1d;--tag-guess-bg:#f9d6d6;
--shadow:0 1px 2px rgba(0,0,0,.05),0 8px 24px -12px rgba(0,0,0,.12)}
@media (prefers-color-scheme:dark){:root:not([data-theme="light"]){color-scheme:dark;
--page:#0d0d0d;--surface:#1a1a19;--surface-2:#222221;--ink:#fff;--ink-2:#c3c2b7;--muted:#898781;
--grid:#2c2c2a;--baseline:#383835;--border:rgba(255,255,255,.10);--accent:#3987e5;
--s1:#3987e5;--s2:#d95926;--s3:#199e70;--better:#3987e5;--worse:#e66767;
--tag-data:#cde2fb;--tag-data-bg:#1c3a60;--tag-bench:#b7d3f6;--tag-bench-bg:#1e2f47;
--tag-est:#fdecc8;--tag-est-bg:#4d3300;--tag-guess:#f9d6d6;--tag-guess-bg:#4d1b1b;
--shadow:none}}
*{box-sizing:border-box}
html{scroll-behavior:smooth;scroll-padding-top:16px}
body{margin:0;background:var(--page);color:var(--ink);font:15px/1.55 system-ui,-apple-system,"Segoe UI",sans-serif;-webkit-font-smoothing:antialiased}
a{color:var(--accent)}
.layout{display:grid;grid-template-columns:232px minmax(0,1fr);gap:0;min-height:100vh}
nav.toc{position:sticky;top:0;height:100vh;overflow:auto;padding:24px 16px;border-right:1px solid var(--border);background:var(--surface)}
nav.toc .brand{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);margin:0 8px 14px}
nav.toc a{display:block;padding:6px 8px;border-radius:6px;color:var(--ink-2);text-decoration:none;font-size:14px}
nav.toc a:hover{background:var(--surface-2);color:var(--ink)}
nav.toc a.active{background:var(--surface-2);color:var(--ink);font-weight:600}
nav.toc a.sub{padding-left:20px;font-size:13px}
nav.toc .print{margin-top:18px;font-size:13px;color:var(--muted)}
main{padding:0 0 64px;min-width:0}
.hero{padding:40px 48px 28px;border-bottom:1px solid var(--border);background:var(--surface)}
.hero .name{margin:0 0 10px;font-size:30px;line-height:1.2;font-weight:700;letter-spacing:-.01em}
.verdict{display:inline-flex;align-items:center;gap:10px;padding:8px 16px 8px 12px;border-radius:999px;font-weight:700;font-size:17px;letter-spacing:.02em;color:#fff;margin:0 0 14px}
.verdict .ic{display:inline-grid;place-items:center;width:26px;height:26px;border-radius:50%;background:rgba(255,255,255,.25);font-size:15px}
.verdict.good{background:var(--good)}.verdict.warning{background:var(--warning);color:#1a1200}.verdict.warning .ic{background:rgba(0,0,0,.12)}
.verdict.serious{background:var(--serious);color:#1a0d00}.verdict.serious .ic{background:rgba(0,0,0,.12)}.verdict.critical{background:var(--critical)}
.meta{display:flex;flex-wrap:wrap;gap:6px 8px;margin:0 0 18px;padding:0;list-style:none}
.meta li{font-size:13px;color:var(--ink-2);background:var(--surface-2);border:1px solid var(--border);border-radius:6px;padding:3px 9px}
.hero blockquote{margin:0;padding:0 0 0 18px;border-left:3px solid var(--accent);font-size:17px;color:var(--ink);max-width:70ch}
.hero blockquote p{margin:0 0 8px}.hero blockquote p:first-child{font-weight:600}
.hero .built{margin:16px 0 0;font-size:12.5px;color:var(--muted)}
section{padding:36px 48px 8px;max-width:1160px}
section h2{font-size:22px;margin:0 0 18px;padding-bottom:8px;border-bottom:1px solid var(--border);letter-spacing:-.01em}
section h3{font-size:17px;margin:26px 0 10px}
section h4{font-size:15px;margin:20px 0 8px}
section h5,section h6{font-size:14px;margin:16px 0 6px}
p{margin:0 0 12px;max-width:80ch}
ul,ol{margin:0 0 12px;padding-left:22px;max-width:80ch}li{margin:3px 0}li>ul,li>ol{margin-top:4px}
blockquote{margin:12px 0;padding:8px 16px;border-left:3px solid var(--baseline);background:var(--surface);color:var(--ink-2)}
blockquote p:last-child{margin-bottom:0}
code{font:12.5px/1.5 ui-monospace,SFMono-Regular,Menlo,Consolas,monospace;background:var(--surface-2);padding:1px 5px;border-radius:4px}
pre{background:var(--surface-2);border:1px solid var(--border);border-radius:8px;padding:12px 14px;overflow-x:auto;max-width:100%}
pre code{background:none;padding:0}
hr{border:0;border-top:1px solid var(--border);margin:20px 0}
.table-wrap{overflow-x:auto;margin:10px 0 18px;border:1px solid var(--border);border-radius:8px;background:var(--surface)}
table{border-collapse:collapse;width:100%;font-size:13.5px}
th,td{padding:7px 10px;border-bottom:1px solid var(--grid);vertical-align:top;text-align:left}
th{font-weight:600;color:var(--ink-2);background:var(--surface-2);white-space:nowrap;font-size:12.5px;letter-spacing:.02em}
tbody tr:last-child td{border-bottom:0}
tbody tr:hover td{background:color-mix(in srgb,var(--surface-2) 60%,transparent)}
td.al-right,th.al-right{text-align:right;font-variant-numeric:tabular-nums}td.al-center,th.al-center{text-align:center}
.tag{display:inline-block;font-size:11px;font-weight:600;line-height:1.4;padding:0 6px;border-radius:4px;vertical-align:baseline;letter-spacing:.01em;white-space:nowrap;max-width:100%}
.tag .tag-detail{font-weight:400;margin-left:4px;white-space:normal}
.tag-data{background:var(--tag-data-bg);color:var(--tag-data)}
.tag-benchmark,.tag-fact{background:var(--tag-bench-bg);color:var(--tag-bench)}
.tag-estimate,.tag-belief,.tag-assumption{background:var(--tag-est-bg);color:var(--tag-est)}
.tag-guess,.tag-unknown{background:var(--tag-guess-bg);color:var(--tag-guess)}
.tag-blocker{background:var(--critical);color:#fff}.tag-major{background:var(--serious);color:#1a0d00}.tag-minor{background:var(--surface-2);color:var(--ink-2)}
a.src{font-size:11.5px;color:var(--muted);text-decoration:none;border-bottom:1px dotted var(--muted)}
.cards{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:6px 0 26px}
.card{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:16px 18px;box-shadow:var(--shadow)}
.card.realistic{outline:2px solid var(--s1);outline-offset:-1px}
.card h3{margin:0 0 12px;font-size:15px;display:flex;align-items:center;gap:8px;text-transform:uppercase;letter-spacing:.06em;color:var(--ink-2)}
.card dl{margin:0}.kv{display:flex;justify-content:space-between;gap:12px;padding:6px 0;border-top:1px solid var(--grid)}
.kv:first-child{border-top:0}.kv dt{color:var(--ink-2);font-size:13px}.kv dd{margin:0;font-variant-numeric:tabular-nums;text-align:right;white-space:nowrap}
.kv.big dd{font-size:20px;font-weight:700;line-height:1.2}.kv.big dt{align-self:end}
.sw{display:inline-block;width:12px;height:12px;border-radius:3px;background:var(--muted);flex:none}
.sw.s1{background:var(--s1)}.sw.s2{background:var(--s2)}.sw.s3{background:var(--s3)}.sw.better{background:var(--better)}.sw.worse{background:var(--worse)}
.charts{display:grid;grid-template-columns:repeat(auto-fit,minmax(420px,1fr));gap:18px;margin:0 0 10px}
.chart-block{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:14px 16px 10px;min-width:0;margin:8px 0 14px}
.chart-block h3{margin:0 0 6px;font-size:14.5px}
figure.chart{margin:0;position:relative}
figure.chart svg{width:100%;height:auto;display:block;overflow:visible}
.legend{display:flex;flex-wrap:wrap;gap:6px 16px;font-size:12.5px;color:var(--ink-2);margin:4px 0 6px}
.lg{display:inline-flex;align-items:center;gap:6px}
svg .grid{stroke:var(--grid);stroke-width:1}svg .baseline{stroke:var(--baseline);stroke-width:1}
svg .zero{stroke:var(--baseline);stroke-width:1.5}svg .ref{stroke:var(--muted);stroke-width:1;stroke-dasharray:4 4}
svg .axis{fill:var(--muted);font-size:11px;font-variant-numeric:tabular-nums}
svg .row-label{fill:var(--ink-2);font-size:12.5px}svg .end-label{fill:var(--ink-2);font-size:12px;font-weight:600}
figure.line svg .axis{font-size:13px}figure.line svg .end-label{font-size:13.5px}
svg .ref-label{fill:var(--ink-2);font-size:12.5px;paint-order:stroke;stroke:var(--surface);stroke-width:4px;stroke-linejoin:round}
svg .series{fill:none;stroke-width:2;stroke-linejoin:round;stroke-linecap:round}
svg .s1{stroke:var(--s1)}svg .s2{stroke:var(--s2)}svg .s3{stroke:var(--s3)}
svg circle.dot{stroke:var(--surface);stroke-width:2}svg circle.s1{fill:var(--s1)}svg circle.s2{fill:var(--s2)}svg circle.s3{fill:var(--s3)}
svg .bar.better{fill:var(--better)}svg .bar.worse{fill:var(--worse)}
svg .xhair{stroke:var(--ink-2);stroke-width:1;stroke-dasharray:3 3;pointer-events:none}
svg .hit{fill:transparent;cursor:crosshair}
.tip{position:absolute;pointer-events:none;background:var(--ink);color:var(--page);font-size:12.5px;padding:8px 10px;border-radius:6px;box-shadow:0 4px 16px rgba(0,0,0,.2);z-index:2;min-width:150px;font-variant-numeric:tabular-nums}
.tip .h{font-weight:600;margin-bottom:4px;opacity:.85}.tip .r{display:flex;justify-content:space-between;gap:14px}.tip .r i{display:inline-block;width:8px;height:8px;border-radius:2px;margin-right:6px}
details.table-view{margin:4px 0 0;font-size:13px}details.table-view summary{cursor:pointer;color:var(--muted)}
.market{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:14px;margin:6px 0 20px}
.tile{background:var(--surface);border:1px solid var(--border);border-radius:12px;padding:14px 16px;display:flex;flex-direction:column;position:relative;overflow:hidden}
.tile::before{content:"";position:absolute;left:0;top:0;bottom:0;width:4px;background:var(--s1);opacity:.35}
.tile.sam::before{opacity:.65}.tile.som::before{opacity:1}
.tile-label{font-size:12px;letter-spacing:.08em;text-transform:uppercase;color:var(--muted);margin-bottom:6px}
.tile-value{font-size:24px;font-weight:700;line-height:1.1}.tile-value2{font-size:17px;font-weight:600;margin-top:8px}
.tile-sub{font-size:12px;color:var(--muted)}.tile small{margin-top:8px;font-size:12px;color:var(--ink-2)}
.callout{border:1px solid var(--border);border-left:4px solid var(--accent);background:var(--surface);border-radius:8px;padding:12px 16px;margin:14px 0}
.callout.warn{border-left-color:var(--warning)}.callout ul{margin:6px 0 0}
details.section-body>summary,details.research>summary{cursor:pointer;font-weight:600;padding:10px 14px;background:var(--surface);border:1px solid var(--border);border-radius:8px;margin:8px 0}
details.research{margin:0 0 6px}details.research[open]>summary{border-radius:8px 8px 0 0;margin-bottom:0}
details.research>div,details.research>*:not(summary){}
details.research[open]{border:1px solid var(--border);border-radius:8px;padding:0 0 4px;background:var(--surface)}
details.research[open]>summary{border:0;border-bottom:1px solid var(--border)}
details.research[open]>*:not(summary){margin-left:14px;margin-right:14px}
footer{padding:28px 48px;font-size:12.5px;color:var(--muted);border-top:1px solid var(--border)}
@media (max-width:980px){
.layout{grid-template-columns:1fr}
nav.toc{position:sticky;top:0;height:auto;border-right:0;border-bottom:1px solid var(--border);padding:10px 12px;display:flex;gap:4px;overflow-x:auto;white-space:nowrap;z-index:3}
nav.toc .brand,nav.toc .print,nav.toc a.sub{display:none}nav.toc a{padding:6px 10px;font-size:13px}
.hero,section,footer{padding-left:20px;padding-right:20px}
.cards,.market{grid-template-columns:1fr}.charts{grid-template-columns:1fr}
}
@media print{
nav.toc,.tip,details.table-view{display:none!important}
.layout{display:block}.hero{padding:0 0 16px}section{padding:16px 0 0;break-inside:auto}
.card,.chart-block,.tile,.table-wrap{break-inside:avoid;box-shadow:none}
details{display:block}details>summary{list-style:none}details:not([open])>*:not(summary){display:block}
body{background:#fff;color:#000;font-size:11.5pt}a{color:inherit;text-decoration:none}
}
"""

JS = r"""
(function(){
  var fmt=function(v,cur,lang){if(v==null)return '—';var s=Math.round(v).toLocaleString(lang==='pt'?'pt-BR':'en-US');return cur?cur+' '+s:s};
  var sym={BRL:'R$',USD:'US$',EUR:'€',GBP:'£'};
  document.querySelectorAll('figure.chart[data-kind="line"]').forEach(function(fig){
    var d=JSON.parse(fig.getAttribute('data-chart'));var svg=fig.querySelector('svg');var hit=svg.querySelector('.hit');
    var xh=svg.querySelector('.xhair');var tip=fig.querySelector('.tip');var cur=d.cur?(sym[d.cur]||d.cur):'';
    function move(ev){
      var r=svg.getBoundingClientRect();var sx=d.w/r.width;var px=(ev.clientX-r.left)*sx;
      var t=(px-d.x0)/(d.x1-d.x0);if(t<0)t=0;if(t>1)t=1;var m=Math.round(t*(d.horizon-1))+1;
      var cx=d.x0+(m-1)/(d.horizon-1)*(d.x1-d.x0);xh.setAttribute('x1',cx);xh.setAttribute('x2',cx);xh.hidden=false;
      var h='<div class="h">'+(d.lang==='pt'?'mês ':'month ')+m+'</div>';
      d.series.forEach(function(s){var v=s.values[m-1];h+='<div class="r"><span><i class="s'+s.slot+'" style="background:var(--s'+s.slot+')"></i>'+s.label+'</span><span>'+fmt(v,cur,d.lang)+'</span></div>'});
      tip.innerHTML=h;tip.hidden=false;
      var left=(cx/sx)+12,top=(ev.clientY-r.top)+12;var fw=fig.getBoundingClientRect().width;
      if(left+tip.offsetWidth>fw-8)left=(cx/sx)-tip.offsetWidth-12;
      tip.style.left=left+'px';tip.style.top=top+'px';
    }
    hit.addEventListener('mousemove',move);hit.addEventListener('touchmove',function(e){move(e.touches[0])},{passive:true});
    hit.addEventListener('mouseleave',function(){tip.hidden=true;xh.hidden=true});
  });
  var links=[].slice.call(document.querySelectorAll('nav.toc a[href^="#"]'));
  var targets=links.map(function(a){return document.getElementById(a.getAttribute('href').slice(1))}).filter(Boolean);
  if('IntersectionObserver' in window&&targets.length){
    var cur=null;var io=new IntersectionObserver(function(es){es.forEach(function(e){if(e.isIntersecting){cur=e.target.id;links.forEach(function(a){a.classList.toggle('active',a.getAttribute('href')==='#'+cur)})}})},{rootMargin:'-10% 0px -80% 0px'});
    targets.forEach(function(t){io.observe(t)});
  }
  window.addEventListener('beforeprint',function(){document.querySelectorAll('details').forEach(function(x){x.setAttribute('open','')})});
})();
"""


def build(dossier: str, out_path: str, lang: str, include_research: bool) -> None:
    L = LABELS[lang]
    readme = read_text(dossier, "README.md")
    if readme is None:
        fail(f"README.md not found in {dossier}")
    r = parse_readme(readme)
    model = read_json(os.path.join(dossier, "work", "model_output.json")) or read_json(os.path.join(dossier, "model_output.json"))
    pivots = []
    for p in sorted(glob.glob(os.path.join(dossier, "work", "model-pivot-*_output.json")) + glob.glob(os.path.join(dossier, "model-pivot-*_output.json"))):
        name = re.sub(r"^model-pivot-|_output\.json$", "", os.path.basename(p)).replace("-", " ")
        pm = read_json(p)
        if pm and "scenarios" in pm:
            pivots.append((name, pm))

    sections: list[tuple[str, str, str]] = []
    missing: list[str] = []
    for fname, sid in SECTIONS:
        md = read_text(dossier, fname)
        if md is None:
            missing.append(fname)
            continue
        title, body = split_title(md)
        label = L[sid]
        inner = md_to_html(body, 1, sid)
        if sid in COLLAPSED_SECTIONS:
            inner = f'<details class="section-body"><summary>{esc(title or label)}</summary>{inner}</details>'
        sections.append((sid, label, f'<section id="{sid}"><h2>{esc(label)}</h2>{inner}</section>'))

    verdict = r["verdict"]
    vcls, vic = VERDICT_STYLE.get(verdict, ("", "•"))
    verdict_html = (f'<div class="verdict {vcls}"><span class="ic">{vic}</span>{esc(L["verdict"])}: {esc(verdict)}</div>'
                    if verdict else "")
    meta_html = "".join(f"<li>{inline(m)}</li>" for m in r["meta"])
    quote_html = f"<blockquote>{md_to_html(r['quote'])}</blockquote>" if r["quote"] else ""

    nav = [f'<a href="#numbers">{esc(L["numbers"])}</a>', f'<a href="#summary">{esc(L["summary"])}</a>']
    nav += [f'<a href="#{sid}">{esc(label)}</a>' for sid, label, _ in sections]
    sources = sources_section(read_text(dossier, "sources.md"), L)
    if sources:
        nav.append(f'<a href="#sources">{esc(L["sources"])}</a>')
    research = research_section(dossier, L) if include_research else ""
    if research:
        nav.append(f'<a href="#research">{esc(L["research"])}</a>')

    summary_html = f'<section id="summary"><h2>{esc(L["summary"])}</h2>{md_to_html(r["body"], 1, "summary")}</section>'
    title = f"{r['name']} — {verdict}" if verdict else r["name"]

    doc = f"""<!doctype html>
<html lang="{'pt-BR' if lang == 'pt' else 'en'}">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{esc(title)}</title>
<style>{CSS}</style>
</head>
<body>
<div class="layout">
<nav class="toc"><div class="brand">{esc(L["menu"])}</div>{"".join(nav)}<div class="print">{esc(L["print"])}: Ctrl/Cmd + P</div></nav>
<main>
<header class="hero">
{verdict_html}
<h1 class="name">{inline(r["name"])}</h1>
<ul class="meta">{meta_html}</ul>
{quote_html}
<p class="built">{esc(L["verdict_meta"].format(date=date.today().isoformat()))}</p>
</header>
{numbers_section(model, pivots, L, lang)}
{summary_html}
{"".join(s[2] for s in sections)}
{sources}
{research}
<footer>{esc(L["footer"])}</footer>
</main>
</div>
<script>{JS}</script>
</body>
</html>
"""
    with open(out_path, "w", encoding="utf-8") as f:
        f.write(doc)
    size_kb = os.path.getsize(out_path) / 1024
    print(f"wrote {out_path} ({size_kb:.0f} KB)")
    if model is None:
        print("warning: " + L["no_model"], file=sys.stderr)
    for m in missing:
        print("warning: " + L["missing"].format(name=m), file=sys.stderr)


def main() -> None:
    ap = argparse.ArgumentParser(description="compile an ideas/<slug>/ dossier into one dossier.html")
    ap.add_argument("dossier", help="path to ideas/<slug>/")
    ap.add_argument("--out", help="output path (default: <dossier>/dossier.html)")
    ap.add_argument("--lang", choices=["en", "pt"], default="en", help="language of the page chrome (labels, cards)")
    ap.add_argument("--no-research", action="store_true", help="leave the raw research notes out of the HTML")
    args = ap.parse_args()
    dossier = args.dossier.rstrip("/")
    if not os.path.isdir(dossier):
        fail(f"not a directory: {dossier}")
    out = args.out or os.path.join(dossier, "dossier.html")
    build(dossier, out, args.lang, not args.no_research)


if __name__ == "__main__":
    main()
